### PR TITLE
Fixed issue #1

### PR DESCRIPTION
**Pull request by JHenneberg**

### CODE REVIEW

**Comment by dongli** [comment]
Intel compiler doesn't support `val => ...` in `select type`? So sad..

**Comment by JHenneberg** [comment]
it is supported. it only has troubles with the character(*). It compiles fine. What makes me wonder is, that the variable val is not even defined and its not causing any error although implicit none is used, not using your compiler or the intel one. I made a few minimal examples I will send to intel fortran and ask.

**Comment by dongli** [comment]
I haven't looked deep at the Fortran standard. The usage of `val => ...` without declaring `val` looks like name aliasing in the `select type` context.

**Comment by JHenneberg** [comment]
you are right it is an [association ](https://software.intel.com/en-us/node/679014) so there is no need to declare it. But that it is not working when returning a character is a bug. In Intel Fortran 19 Beta it is working.

**Comment by dongli** [comment]
Thanks for your clarification! Merge it to play with old Intel compiler.

**Pull request merged**
